string1 = """[INTERACTION:PARAGON_IRON"""
string2 = """]
	[I_SOURCE:SECRET]
		[IS_NAME:the method to become an iron paragon]
		[IS_SECRET_GOAL:IMMORTALITY]
		[IS_SECRET:SUPERNATURAL_LEARNING_POSSIBLE]
		[IS_SECRET:MUNDANE_RESEARCH_POSSIBLE]
		[IS_SECRET:MUNDANE_TEACHING_POSSIBLE]
	[I_SOURCE:DEITY]
		[IS_USAGE_HINT:MAJOR_CURSE]
		[IS_HIST_STRING_1: must have blessed ]
		[IS_HIST_STRING_2: as they were selected to become an iron paragon]

	[I_TARGET:A:CREATURE]
		[IT_LOCATION:CONTEXT_CREATURE]
		[IT_AFFECTED_CREATURE:DWARF:ALL]
		
		[IT_CANNOT_HAVE_SYNDROME_CLASS:VAMPCURSE][IT_CANNOT_HAVE_SYNDROME_CLASS:WERECURSE][IT_CANNOT_HAVE_SYNDROME_CLASS:NECROMANCER][IT_CANNOT_HAVE_SYNDROME_CLASS:PARAGON]
	[I_EFFECT:ADD_SYNDROME]
		[IE_TARGET:A]
		[IE_IMMEDIATE]
		
	
		[SYNDROME]
		[SYN_CLASS:PARAGON]


	[SYNDROME]
	[SYN_CLASS:WERECURSE]
	[SYN_CLASS:PARAGON]
	[SYN_AFFECTED_CREATURE:DWARF:FEMALE]
	[CE_BODY_TRANSFORMATION:PROB:100:START:0]
		[CE:CREATURE:IRON_PARAGON:FEMALE]
	[CE_PHYS_ATT_CHANGE:STRENGTH:200:0:TOUGHNESS:200:0:START:0:ABRUPT]
	[CE_ADD_TAG:STERILE:START:0:ABRUPT]

	[SYNDROME]
	[SYN_CLASS:WERECURSE]
	[SYN_CLASS:PARAGON]
	[SYN_AFFECTED_CREATURE:DWARF:MALE]
	[CE_BODY_TRANSFORMATION:PROB:100:START:0]
		[CE:CREATURE:IRON_PARAGON:MALE]
	[CE_PHYS_ATT_CHANGE:STRENGTH:200:0:TOUGHNESS:200:0:START:0:ABRUPT]
	[CE_ADD_TAG:STERILE:START:0:ABRUPT]

[INTERACTION:PARAGON_STEEL"""
string3 = """]
	[I_SOURCE:SECRET]
		[IS_NAME:the method to become a steel paragon]
		[IS_SECRET_GOAL:IMMORTALITY]
		[IS_SPHERE:METALS]
		[IS_SECRET:SUPERNATURAL_LEARNING_POSSIBLE]
		[IS_SECRET:MUNDANE_RESEARCH_POSSIBLE]
		[IS_SECRET:MUNDANE_TEACHING_POSSIBLE]
	[I_SOURCE:DEITY]
		[IS_USAGE_HINT:MAJOR_CURSE]
		[IS_HIST_STRING_1: must have blessed ]
		[IS_HIST_STRING_2: as they were selected to become a steel paragon]

	[I_TARGET:A:CREATURE]
		[IT_LOCATION:CONTEXT_CREATURE]
		[IT_AFFECTED_CREATURE:DWARF:ALL]
		
		[IT_CANNOT_HAVE_SYNDROME_CLASS:VAMPCURSE][IT_CANNOT_HAVE_SYNDROME_CLASS:WERECURSE][IT_CANNOT_HAVE_SYNDROME_CLASS:NECROMANCER][IT_CANNOT_HAVE_SYNDROME_CLASS:PARAGON]
	[I_EFFECT:ADD_SYNDROME]
		[IE_TARGET:A]
		[IE_IMMEDIATE]
		
	
		[SYNDROME]
		[SYN_CLASS:PARAGON]


	[SYNDROME]
	[SYN_CLASS:WERECURSE]
	[SYN_CLASS:PARAGON]
	[SYN_AFFECTED_CREATURE:DWARF:FEMALE]
	[CE_BODY_TRANSFORMATION:PROB:100:START:0]
		[CE:CREATURE:STEEL_PARAGON:FEMALE]
	[CE_PHYS_ATT_CHANGE:STRENGTH:200:0:TOUGHNESS:200:0:START:0:ABRUPT]
	[CE_ADD_TAG:STERILE:START:0:ABRUPT]

	[SYNDROME]
	[SYN_CLASS:WERECURSE]
	[SYN_CLASS:PARAGON]
	[SYN_AFFECTED_CREATURE:DWARF:MALE]
	[CE_BODY_TRANSFORMATION:PROB:100:START:0]
		[CE:CREATURE:STEEL_PARAGON:MALE]
	[CE_PHYS_ATT_CHANGE:STRENGTH:200:0:TOUGHNESS:200:0:START:0:ABRUPT]
	[CE_ADD_TAG:STERILE:START:0:ABRUPT]"""

for x in range(1,11):
    print(string1+str(x)+string2+str(x)+string3)